[tool.poetry]
name = "github-action-test"
version = "0.1.0"
description = ""
authors = ["colyerdeng <shawndeng1109@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
