name: hello_word
on:
  push:
    branches:
      - main
  workflow_dispatch:
    steps:
      - uses: actions/checkout@v3

      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: op://PERSONAL_ACCESS_TOKEN/credential

      - name: Print masked secret
        run: 'echo "Secret: $SECRET"'
