name: Bump version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - uses: actions/checkout@v3

      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v2
        with:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: setup credentials
        id: load-credentials
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          PERSONAL_ACCESS_TOKEN: op://PERSONAL_ACCESS_TOKEN/credential

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ steps.load-credentials.outputs.PERSONAL_ACCESS_TOKEN }}
          branch: main
